### ISSUE TITLE
New Line not working on the item lore of pipe in/output, settings book...

### ISSUE THREAD

**Issue by BijuuKrunos** [Minebench/Pipes#10]
### What is happening?

Using newest Version on paper 1.21.1, i am not sure if that even worked in the past but how ever i try i cant get it to work.

Tried:

lore: '&bItem&8-&bOutput for an Item&8-&bPipe&8. \n &7You can find help at &8/&6pipe'

lore: -|
'&bItem&8-&bOutput for an Item&8-&bPipe&8.'
'&7You can find help at &8/&6pipe'

lore: |
&bItem&8-&bOutput for an Item&8-&bPipe&8.
&7You can find help at &8/&6pipe

### What did you expect to happen?

that the text of the item lore get to a new line.

### Version

Pipe 324

### Config

```YAML
pipeCacheDuration: 600 #s
pipeCacheSize: 1000 #number of cached inputs
transferCooldown: 60 #ticks
transferCount: 10 #max amounts of stacks that one pipe can transfer
inputToOutputRatio: 0.0 #ratio for max transfers per pipe per move task
pistonUpdateCheck: true
convertToBlockInfoOnChunkLoad: false
customModelDataOffset: 1
defaultLocale: en
dispenserRecipe:
  DISPENSER: 1
  HOPPER: 1
  BOOK: 1
dropperRecipe:
  DROPPER: 1
  HOPPER: 1
  BOOK: 1
chunkLoaderRecipe:
  FURNACE: 1
  OBSIDIAN: 1
  GOLD_BLOCK: 1
maxPipeLength: 256
maxPipeOutputs: 128
gui:
  true: "PRISMARINE_SHARD:63"
  false: "PRISMARINE_SHARD:67"
  input: "PRISMARINE_SHARD:62"
  whitelist:
    true: "PRISMARINE_SHARD:23"
    false: "PRISMARINE_SHARD:21"
  filler: "PRISMARINE_SHARD:1"
  copy: "WRITABLE_BOOK"
```

### Server/system Version

paper-196

### Log

```shell
[Put your log here]
```

### What other programs/plugins are you running?

dont think you need this :)

### Additional context

Ohh and how do i use the language key feature you added in? For Ressourcepacks? tried it, but did not worked.
