### ISSUE TITLE
Bedrock Crash

### ISSUE THREAD

**Issue by BijuuKrunos** [Minebench/Pipes#4]
#### Used Version
 Pipes v1.5-SNAPSHOT (build 292)
 
 
#### Config

 ```yaml
 pipeCacheDuration: 600 #s
pipeCacheSize: 1000 #number of cached inputs
transferCooldown: 100 #ticks
transferCount: 10 #max amounts of stacks that one pipe can transfer
inputToOutputRatio: 0.0 #ratio for max transfers per pipe per move task
pistonUpdateCheck: true
convertToBlockInfoOnChunkLoad: false
customModelDataOffset: 1
dispenserRecipe:
  DISPENSER: 1
  HOPPER: 1
  BOOK: 1
dropperRecipe:
  DROPPER: 1
  HOPPER: 1
  BOOK: 1
maxPipeLength: 256
maxPipeOutputs: 128
gui:
  true: "LIME_WOOL"
  false: "RED_WOOL"
  input: "YELLOW_WOOL"
  whitelist:
    true: "WHITE_WOOL"
    false: "BLACK_WOOL"
  copy: "WRITABLE_BOOK"
 ```

#### What is happening?
If you have Geyser installed on the Bungeecord Server (perhaps on the paper server directly too) the player crashes by opening the inventory. It has to do something with the recipes,

#### What did you expect to happen?
Not Crashing the Bedrock Players Client

#### Additional context
![image](https://user-images.githubusercontent.com/38471938/208983710-99943bf2-c751-4eac-8e3c-44c354c5f079.png)
